-- US Price Catalog
-- Generated: 2026-02-05T19:31:51.148Z
-- Source: HomeAdvisor/HomeGuide estimates

-- Clear existing data
TRUNCATE TABLE price_catalog_us;

-- Insert new data
INSERT INTO price_catalog_us (category, work_name, unit, price_min, price_avg, price_max, region, region_name, source, confidence)
VALUES
  ('Bathroom', 'Bathroom remodel', 'project', 8100, 16200, 33750, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 7500, 15000, 31250, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 6600, 13200, 27500, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 5700, 11400, 23750, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 5400, 10800, 22500, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 6900, 13800, 28750, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 5100, 10200, 21250, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 7200, 14400, 30000, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 5700, 11400, 23750, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathroom remodel', 'project', 6600, 13200, 27500, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 9.45, 20.25, 33.75, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 8.75, 18.75, 31.25, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 7.7, 16.5, 27.5, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 6.65, 14.25, 23.75, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 6.3, 13.5, 22.5, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 8.05, 17.25, 28.75, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 5.95, 12.75, 21.25, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 8.4, 18, 30, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 6.65, 14.25, 23.75, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Tile installation', 'sq ft', 7.7, 16.5, 27.5, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 202.5, 472.5, 810, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 187.5, 437.5, 750, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 165, 385, 660, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 142.5, 332.5, 570, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 135, 315, 540, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 172.5, 402.5, 690, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 127.5, 297.5, 510, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 180, 420, 720, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 142.5, 332.5, 570, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Toilet installation', 'unit', 165, 385, 660, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1620, 4050, 8100, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1500, 3750, 7500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1320, 3300, 6600, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1140, 2850, 5700, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1080, 2700, 5400, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1380, 3450, 6900, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1020, 2550, 5100, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1440, 3600, 7200, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1140, 2850, 5700, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Shower installation', 'unit', 1320, 3300, 6600, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1890, 4725, 9450, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1750, 4375, 8750, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1540, 3850, 7700, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1330, 3325, 6650, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1260, 3150, 6300, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1610, 4025, 8050, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1190, 2975, 5950, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1680, 4200, 8400, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1330, 3325, 6650, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Bathtub installation', 'unit', 1540, 3850, 7700, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 405, 1080, 2025, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 375, 1000, 1875, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 330, 880, 1650, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 285, 760, 1425, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 270, 720, 1350, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 345, 920, 1725, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 255, 680, 1275, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 360, 960, 1800, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 285, 760, 1425, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Bathroom', 'Vanity installation', 'unit', 330, 880, 1650, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 20250, 40500, 81000, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 18750, 37500, 75000, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 16500, 33000, 66000, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 14250, 28500, 57000, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 13500, 27000, 54000, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 17250, 34500, 69000, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 12750, 25500, 51000, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 18000, 36000, 72000, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 14250, 28500, 57000, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen remodel', 'project', 16500, 33000, 66000, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 135, 270, 540, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 125, 250, 500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 110, 220, 440, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 95, 190, 380, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 90, 180, 360, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 115, 230, 460, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 85, 170, 340, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 120, 240, 480, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 95, 190, 380, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Cabinet installation', 'linear ft', 110, 220, 440, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 54, 101.25, 202.5, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 50, 93.75, 187.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 44, 82.5, 165, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 38, 71.25, 142.5, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 36, 67.5, 135, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 46, 86.25, 172.5, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 34, 63.75, 127.5, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 48, 90, 180, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 38, 71.25, 142.5, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Countertop installation', 'sq ft', 44, 82.5, 165, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 20.25, 40.5, 67.5, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 18.75, 37.5, 62.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 16.5, 33, 55, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 14.25, 28.5, 47.5, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 13.5, 27, 45, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 17.25, 34.5, 57.5, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 12.75, 25.5, 42.5, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 18, 36, 60, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 14.25, 28.5, 47.5, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Backsplash installation', 'sq ft', 16.5, 33, 55, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 270, 540, 945, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 250, 500, 875, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 220, 440, 770, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 190, 380, 665, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 180, 360, 630, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 230, 460, 805, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 170, 340, 595, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 240, 480, 840, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 190, 380, 665, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Kitchen', 'Kitchen sink installation', 'unit', 220, 440, 770, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 8.1, 16.2, 27, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 7.5, 15, 25, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 6.6, 13.2, 22, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 5.7, 11.4, 19, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 5.4, 10.8, 18, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 6.9, 13.8, 23, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 5.1, 10.2, 17, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 7.2, 14.4, 24, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 5.7, 11.4, 19, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Hardwood floor installation', 'sq ft', 6.6, 13.2, 22, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 4.05, 9.45, 16.2, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 3.75, 8.75, 15, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 3.3, 7.7, 13.2, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 2.85, 6.65, 11.4, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 2.7, 6.3, 10.8, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 3.45, 8.05, 13.8, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 2.55, 5.95, 10.2, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 3.6, 8.4, 14.4, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 2.85, 6.65, 11.4, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Laminate floor installation', 'sq ft', 3.3, 7.7, 13.2, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 2.7, 6.75, 13.5, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 2.5, 6.25, 12.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 2.2, 5.5, 11, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 1.9, 4.75, 9.5, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 1.8, 4.5, 9, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 2.3, 5.75, 11.5, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 1.7, 4.25, 8.5, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 2.4, 6, 12, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 1.9, 4.75, 9.5, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Vinyl floor installation', 'sq ft', 2.2, 5.5, 11, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 4.05, 8.1, 16.2, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 3.75, 7.5, 15, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 3.3, 6.6, 13.2, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 2.85, 5.7, 11.4, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 2.7, 5.4, 10.8, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 3.45, 6.9, 13.8, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 2.55, 5.1, 10.2, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 3.6, 7.2, 14.4, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 2.85, 5.7, 11.4, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Carpet installation', 'sq ft', 3.3, 6.6, 13.2, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 9.45, 20.25, 33.75, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 8.75, 18.75, 31.25, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 7.7, 16.5, 27.5, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 6.65, 14.25, 23.75, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 6.3, 13.5, 22.5, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 8.05, 17.25, 28.75, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 5.95, 12.75, 21.25, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 8.4, 18, 30, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 6.65, 14.25, 23.75, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Flooring', 'Tile floor installation', 'sq ft', 7.7, 16.5, 27.5, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 2.03, 4.05, 6.75, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.88, 3.75, 6.25, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.65, 3.3, 5.5, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.42, 2.85, 4.75, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.35, 2.7, 4.5, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.73, 3.45, 5.75, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.27, 2.55, 4.25, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.8, 3.6, 6, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.42, 2.85, 4.75, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Interior painting', 'sq ft', 1.65, 3.3, 5.5, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 2.7, 5.4, 9.45, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 2.5, 5, 8.75, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 2.2, 4.4, 7.7, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 1.9, 3.8, 6.65, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 1.8, 3.6, 6.3, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 2.3, 4.6, 8.05, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 1.7, 3.4, 5.95, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 2.4, 4.8, 8.4, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 1.9, 3.8, 6.65, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Exterior painting', 'sq ft', 2.2, 4.4, 7.7, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 40.5, 81, 135, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 37.5, 75, 125, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 33, 66, 110, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 28.5, 57, 95, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 27, 54, 90, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 34.5, 69, 115, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 25.5, 51, 85, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 36, 72, 120, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 28.5, 57, 95, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Cabinet painting', 'linear ft', 33, 66, 110, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 1.35, 2.7, 5.4, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 1.25, 2.5, 5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 1.1, 2.2, 4.4, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 0.95, 1.9, 3.8, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 0.9, 1.8, 3.6, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 1.15, 2.3, 4.6, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 0.85, 1.7, 3.4, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 1.2, 2.4, 4.8, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 0.95, 1.9, 3.8, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Painting', 'Ceiling painting', 'sq ft', 1.1, 2.2, 4.4, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 2025, 3375, 5400, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1875, 3125, 5000, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1650, 2750, 4400, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1425, 2375, 3800, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1350, 2250, 3600, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1725, 2875, 4600, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1275, 2125, 3400, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1800, 3000, 4800, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1425, 2375, 3800, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Electrical panel upgrade', 'project', 1650, 2750, 4400, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 135, 270, 472.5, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 125, 250, 437.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 110, 220, 385, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 95, 190, 332.5, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 90, 180, 315, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 115, 230, 402.5, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 85, 170, 297.5, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 120, 240, 420, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 95, 190, 332.5, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Outlet installation', 'unit', 110, 220, 385, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 101.25, 270, 540, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 93.75, 250, 500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 82.5, 220, 440, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 71.25, 190, 380, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 67.5, 180, 360, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 86.25, 230, 460, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 63.75, 170, 340, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 90, 240, 480, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 71.25, 190, 380, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Light fixture installation', 'unit', 82.5, 220, 440, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 202.5, 405, 675, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 187.5, 375, 625, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 165, 330, 550, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 142.5, 285, 475, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 135, 270, 450, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 172.5, 345, 575, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 127.5, 255, 425, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 180, 360, 600, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 142.5, 285, 475, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Ceiling fan installation', 'unit', 165, 330, 550, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 168.75, 337.5, 540, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 156.25, 312.5, 500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 137.5, 275, 440, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 118.75, 237.5, 380, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 112.5, 225, 360, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 143.75, 287.5, 460, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 106.25, 212.5, 340, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 150, 300, 480, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 118.75, 237.5, 380, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Electrical', 'Recessed lighting installation', 'unit', 137.5, 275, 440, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 1080, 2025, 3375, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 1000, 1875, 3125, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 880, 1650, 2750, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 760, 1425, 2375, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 720, 1350, 2250, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 920, 1725, 2875, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 680, 1275, 2125, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 960, 1800, 3000, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 760, 1425, 2375, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Water heater installation', 'unit', 880, 1650, 2750, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 13.5, 33.75, 67.5, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 12.5, 31.25, 62.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 11, 27.5, 55, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 9.5, 23.75, 47.5, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 9, 22.5, 45, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 11.5, 28.75, 57.5, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 8.5, 21.25, 42.5, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 12, 30, 60, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 9.5, 23.75, 47.5, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Pipe repair', 'linear ft', 11, 27.5, 55, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 135, 303.75, 540, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 125, 281.25, 500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 110, 247.5, 440, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 95, 213.75, 380, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 90, 202.5, 360, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 115, 258.75, 460, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 85, 191.25, 340, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 120, 270, 480, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 95, 213.75, 380, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Drain cleaning', 'project', 110, 247.5, 440, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 202.5, 405, 675, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 187.5, 375, 625, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 165, 330, 550, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 142.5, 285, 475, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 135, 270, 450, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 172.5, 345, 575, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 127.5, 255, 425, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 180, 360, 600, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 142.5, 285, 475, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Faucet installation', 'unit', 165, 330, 550, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 202.5, 472.5, 810, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 187.5, 437.5, 750, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 165, 385, 660, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 142.5, 332.5, 570, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 135, 315, 540, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 172.5, 402.5, 690, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 127.5, 297.5, 510, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 180, 420, 720, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 142.5, 332.5, 570, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Plumbing', 'Garbage disposal installation', 'unit', 165, 385, 660, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 4050, 7425, 13500, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 3750, 6875, 12500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 3300, 6050, 11000, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 2850, 5225, 9500, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 2700, 4950, 9000, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 3450, 6325, 11500, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 2550, 4675, 8500, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 3600, 6600, 12000, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 2850, 5225, 9500, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'AC installation', 'unit', 3300, 6050, 11000, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 3375, 6075, 10800, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 3125, 5625, 10000, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 2750, 4950, 8800, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 2375, 4275, 7600, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 2250, 4050, 7200, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 2875, 5175, 9200, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 2125, 3825, 6800, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 3000, 5400, 9600, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 2375, 4275, 7600, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Furnace installation', 'unit', 2750, 4950, 8800, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 405, 675, 1080, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 375, 625, 1000, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 330, 550, 880, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 285, 475, 760, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 270, 450, 720, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 345, 575, 920, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 255, 425, 680, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 360, 600, 960, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 285, 475, 760, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Duct cleaning', 'project', 330, 550, 880, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 135, 337.5, 540, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 125, 312.5, 500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 110, 275, 440, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 95, 237.5, 380, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 90, 225, 360, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 115, 287.5, 460, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 85, 212.5, 340, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 120, 300, 480, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 95, 237.5, 380, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('HVAC', 'Thermostat installation', 'unit', 110, 275, 440, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 5.4, 10.8, 20.25, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 5, 10, 18.75, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 4.4, 8.8, 16.5, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 3.8, 7.6, 14.25, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 3.6, 7.2, 13.5, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 4.6, 9.2, 17.25, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 3.4, 6.8, 12.75, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 4.8, 9.6, 18, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 3.8, 7.6, 14.25, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof replacement', 'sq ft', 4.4, 8.8, 16.5, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 405, 1215, 2700, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 375, 1125, 2500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 330, 990, 2200, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 285, 855, 1900, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 270, 810, 1800, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 345, 1035, 2300, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 255, 765, 1700, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 360, 1080, 2400, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 285, 855, 1900, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Roof repair', 'project', 330, 990, 2200, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 6.75, 13.5, 27, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 6.25, 12.5, 25, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 5.5, 11, 22, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 4.75, 9.5, 19, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 4.5, 9, 18, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 5.75, 11.5, 23, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 4.25, 8.5, 17, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 6, 12, 24, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 4.75, 9.5, 19, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Roofing', 'Gutter installation', 'linear ft', 5.5, 11, 22, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 405, 877.5, 1620, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 375, 812.5, 1500, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 330, 715, 1320, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 285, 617.5, 1140, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 270, 585, 1080, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 345, 747.5, 1380, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 255, 552.5, 1020, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 360, 780, 1440, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 285, 617.5, 1140, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Window replacement', 'unit', 330, 715, 1320, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 337.5, 675, 1215, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 312.5, 625, 1125, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 275, 550, 990, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 237.5, 475, 855, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 225, 450, 810, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 287.5, 575, 1035, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 212.5, 425, 765, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 300, 600, 1080, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 237.5, 475, 855, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Door installation', 'unit', 275, 550, 990, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 1350, 2700, 5400, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 1250, 2500, 5000, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 1100, 2200, 4400, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 950, 1900, 3800, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 900, 1800, 3600, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 1150, 2300, 4600, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 850, 1700, 3400, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 1200, 2400, 4800, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 950, 1900, 3800, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Windows & Doors', 'Sliding door installation', 'unit', 1100, 2200, 4400, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 2.03, 4.05, 6.75, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.88, 3.75, 6.25, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.65, 3.3, 5.5, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.42, 2.85, 4.75, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.35, 2.7, 4.5, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.73, 3.45, 5.75, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.27, 2.55, 4.25, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.8, 3.6, 6, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.42, 2.85, 4.75, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall installation', 'sq ft', 1.65, 3.3, 5.5, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 2.7, 5.4, 10.8, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 2.5, 5, 10, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 2.2, 4.4, 8.8, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 1.9, 3.8, 7.6, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 1.8, 3.6, 7.2, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 2.3, 4.6, 9.2, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 1.7, 3.4, 6.8, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 2.4, 4.8, 9.6, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 1.9, 3.8, 7.6, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Drywall repair', 'sq ft', 2.2, 4.4, 8.8, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 1.35, 2.7, 5.4, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 1.25, 2.5, 5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 1.1, 2.2, 4.4, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 0.95, 1.9, 3.8, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 0.9, 1.8, 3.6, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 1.15, 2.3, 4.6, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 0.85, 1.7, 3.4, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 1.2, 2.4, 4.8, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 0.95, 1.9, 3.8, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Drywall', 'Popcorn ceiling removal', 'sq ft', 1.1, 2.2, 4.4, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 20.25, 47.25, 81, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 18.75, 43.75, 75, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 16.5, 38.5, 66, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 14.25, 33.25, 57, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 13.5, 31.5, 54, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 17.25, 40.25, 69, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 12.75, 29.75, 51, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 18, 42, 72, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 14.25, 33.25, 57, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Deck building', 'sq ft', 16.5, 38.5, 66, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 20.25, 40.5, 67.5, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 18.75, 37.5, 62.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 16.5, 33, 55, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 14.25, 28.5, 47.5, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 13.5, 27, 45, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 17.25, 34.5, 57.5, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 12.75, 25.5, 42.5, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 18, 36, 60, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 14.25, 28.5, 47.5, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Fence installation', 'linear ft', 16.5, 33, 55, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 8.1, 13.5, 24.3, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 7.5, 12.5, 22.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 6.6, 11, 19.8, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 5.7, 9.5, 17.1, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 5.4, 9, 16.2, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 6.9, 11.5, 20.7, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 5.1, 8.5, 15.3, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 7.2, 12, 21.6, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 5.7, 9.5, 17.1, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Concrete driveway', 'sq ft', 6.6, 11, 19.8, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 6.75, 13.5, 24.3, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 6.25, 12.5, 22.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 5.5, 11, 19.8, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 4.75, 9.5, 17.1, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 4.5, 9, 16.2, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 5.75, 11.5, 20.7, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 4.25, 8.5, 15.3, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 6, 12, 21.6, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 4.75, 9.5, 17.1, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Exterior', 'Siding installation', 'sq ft', 5.5, 11, 19.8, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 2.7, 6.75, 13.5, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 2.5, 6.25, 12.5, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 2.2, 5.5, 11, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 1.9, 4.75, 9.5, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 1.8, 4.5, 9, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 2.3, 5.75, 11.5, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 1.7, 4.25, 8.5, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 2.4, 6, 12, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 1.9, 4.75, 9.5, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Demolition', 'sq ft', 2.2, 5.5, 11, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 270, 675, 1350, 'US-NY-NYC', 'New York City, NY', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 250, 625, 1250, 'US-CA-LA', 'Los Angeles, CA', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 220, 550, 1100, 'US-IL-CHI', 'Chicago, IL', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 190, 475, 950, 'US-TX-HOU', 'Houston, TX', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 180, 450, 900, 'US-AZ-PHX', 'Phoenix, AZ', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 230, 575, 1150, 'US-PA-PHL', 'Philadelphia, PA', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 170, 425, 850, 'US-TX-SA', 'San Antonio, TX', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 240, 600, 1200, 'US-CA-SD', 'San Diego, CA', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 190, 475, 950, 'US-TX-DAL', 'Dallas, TX', 'homeadvisor_estimate', 0.7),
  ('Demolition', 'Debris removal', 'project', 220, 550, 1100, 'US-FL-MIA', 'Miami, FL', 'homeadvisor_estimate', 0.7);
